site_name: Моё портфолио по программированию
site_url: https://ваш-username.github.io/portfolio/ 
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Главная: index.md
  - Лабораторные работы:
    - labs/lab1.md
    - labs/lab2.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences